language: php
php:
    - 7.0
    - 7.1
#before_install:
#    - php /home/travis/.phpenv/versions/5.4.25/bin/composer.phar self-update
#before_script:
install:
    - composer install

script:
    - phpunit --configuration phpunit.xml.dist --coverage-text
