language: php
php:
    - 5.6
    - 7.0
    - 7.1
before_install:
    - php /home/travis/.phpenv/versions/5.4.25/bin/composer.phar self-update
before_script:
    - composer install

script: php unit --configuration phpunit.xml --coverage-text
