services:
    api.scope_listener_reader:
        class: ApiBundle\Listener\ScopeAnnotationReaderListener
        public: true
        tags:
            - { name: kernel.event_subscriber }
        arguments:
            - '@api.annotation_reader'
            - '@api.allowed_scopes_repository'
            - '@api.transformer_scope_repository'

    api.scope_listener:
        class: ApiBundle\Listener\ScopeListener
        public: true
        tags:
            - { name: kernel.event_subscriber }
        arguments:
            - '@api.transformer_scope_repository'

    api.nelmio_api_doc.scope_handler:
        class: ApiBundle\Documentation\ScopeAnnotationHandler
        public: true
        tags:
            - { name: nelmio_api_doc.extractor.handler }


    api.annotation_reader:
        class: ApiBundle\Reflection\AnnotationsReader
        public: true
        arguments:
            - '@annotations.reader'