services:
    #Transformer
    api.main_transformer:
        class: ApiBundle\Transformer\Transformer
        public: true
        arguments:
            - '@api.transformer_scope_repository'

    abstract.transformer:
        class: ApiBundle\Transformer\AbstractTransformer
        public: true
        abstract: true
        calls:
            - [setTransformer, ['@api.main_transformer']]

    api.transformer_scope_repository:
        class: ApiBundle\Transformer\Scope\ScopeRepository

    api.allowed_scopes_repository:
        class: ApiBundle\Transformer\Scope\AllowedScopesRepository

    api.abstract_transformer_scope:
        class: ApiBundle\Transformer\Scope\AbstractTransformerScope
        abstract: true
        calls:
            - [setTransformer, ['@api.main_transformer']]

    #Voter
    api.abstract_voter:
        class: ApiBundle\Security\Voter\AbstractVoter
        abstract: true
        public: false
        arguments:
            - '@security.access.decision_manager'
            - '@doctrine.orm.entity_manager'

    #Form Type
    api.form_type_persei_file_type:
        class: ApiBundle\Form\Type\PerseiFileType
        tags:
            - { name: form.type }

    api.form_extension_persei_file_type:
        class: ApiBundle\Form\Extension\PerseiFileTypeExtension
        tags:
            - { name: form.type_extension, extended_type: ApiBundle\Form\Type\PerseiFileType }

    api.form_handler_persei_file_handler:
        class: ApiBundle\Form\Handler\PerseiFileHandler
        arguments:
            - '@api.managger_file_manager'
        public: true

    api.managger_file_manager:
        class: ApiBundle\Manager\FileManager
        arguments:
            - '%kernel.project_dir%'
